import { Button, Modal } from 'antd';
import type { UseResourceFirestoreDataReturnType } from 'hooks/useResourceFirestoreData';
import { useMemo, useState } from 'react';
import type { SuspectCard, SuspectExtendedInfo } from 'types';

type NewSuspectFlowProps = {
  suspects: Dictionary<SuspectCard>;
  suspectsExtendedInfos: Dictionary<SuspectExtendedInfo>;
  addSuspectEntryToUpdate: UseResourceFirestoreDataReturnType<SuspectCard>['addEntryToUpdate'];
  addExtendedInfoEntryToUpdate: UseResourceFirestoreDataReturnType<SuspectExtendedInfo>['addEntryToUpdate'];
};

export function NewSuspectFlow({
  suspects,
  suspectsExtendedInfos,
  addSuspectEntryToUpdate,
  addExtendedInfoEntryToUpdate,
}: NewSuspectFlowProps) {
  const [open, setOpen] = useState(false);

  const nextId = useMemo(() => {
    const ids = Object.values(suspects)
      .map((s) => Number.parseInt(s.id.split('-')[1], 10))
      .filter((n) => !isNaN(n));
    if (ids.length === 0) return 'us-000';
    return `us-${(Math.max(...ids) + 1).toString().padStart(3, '0')}`;
  }, [suspects]);
  console.log(nextId);

  return (
    <>
      <Button block onClick={() => setOpen(true)}>
        New Suspect
      </Button>
      <Modal onCancel={() => setOpen(false)} onOk={() => setOpen(false)} open={open} title="New Suspect">
        ???
      </Modal>
    </>
  );
}

const NAME_SUGGESTIONS = [
  { en: 'Abner', pt: 'Abner' },
  { en: 'Abraham', pt: 'Abraão' },
  { en: 'Agatha', pt: 'Ágata' },
  { en: 'Amos', pt: 'Amós' },
  { en: 'Anselm', pt: 'Anselmo' },
  { en: 'Arlo', pt: 'Arlo' },
  { en: 'Ashley', pt: 'Ariane' },
  { en: 'Augustus', pt: 'Augusto' },
  { en: 'Aurora', pt: 'Aurora' },
  { en: 'Balthazar', pt: 'Baltazar' },
  { en: 'Barbara', pt: 'Bárbara' },
  { en: 'Bertram', pt: 'Belmiro' },
  { en: 'Bianca', pt: 'Bianca' },
  { en: 'Boniface', pt: 'Bonifácio' },
  { en: 'Brendan', pt: 'Breno' },
  { en: 'Callum', pt: 'Calu' },
  { en: 'Cassandra', pt: 'Cassandra' },
  { en: 'Cassian', pt: 'Cassiano' },
  { en: 'Christopher', pt: 'Cristóvão' },
  { en: 'Clarence', pt: 'Clarêncio' },
  { en: 'Clement', pt: 'Clemente' },
  { en: 'Clyde', pt: 'Clodoaldo' },
  { en: 'Colton', pt: 'Colton' },
  { en: 'Cora', pt: 'Cora' },
  { en: 'Cornelius', pt: 'Cornélio' },
  { en: 'Cynthia', pt: 'Cíntia' },
  { en: 'Cyrus', pt: 'Ciro' },
  { en: 'Daniel', pt: 'Daniel' },
  { en: 'Daphne', pt: 'Dafne' },
  { en: 'Dara', pt: 'Dara' },
  { en: 'Darcy', pt: 'Darci' },
  { en: 'Darnell', pt: 'Darnel' },
  { en: 'Demetrius', pt: 'Demétrio' },
  { en: 'Desmond', pt: 'Desidério' },
  { en: 'Diana', pt: 'Diana' },
  { en: 'Diego', pt: 'Diego' },
  { en: 'Dina', pt: 'Dina' },
  { en: 'Donatello', pt: 'Donatelo' },
  { en: 'Dora', pt: 'Dora' },
  { en: 'Duncan', pt: 'Duarte' },
  { en: 'Dustin', pt: 'Dustin' },
  { en: 'Dylan', pt: 'Dylan' },
  { en: 'Edmund', pt: 'Edmundo' },
  { en: 'Edward', pt: 'Eduardo' },
  { en: 'Edwin', pt: 'Edwin' },
  { en: 'Eileen', pt: 'Eline' },
  { en: 'Elaine', pt: 'Elaine' },
  { en: 'Elizabeth', pt: 'Elisabete' },
  { en: 'Eloise', pt: 'Eloísa' },
  { en: 'Elsa', pt: 'Elsa' },
  { en: 'Emanuel', pt: 'Emanuel' },
  { en: 'Emery', pt: 'Emery' },
  { en: 'Emerson', pt: 'Emerson' },
  { en: 'Emil', pt: 'Emílio' },
  { en: 'Emily', pt: 'Emília' },
  { en: 'Emma', pt: 'Ema' },
  { en: 'Enoch', pt: 'Enoque' },
  { en: 'Erasmus', pt: 'Erasmo' },
  { en: 'Eric', pt: 'Erico' },
  { en: 'Esmond', pt: 'Esmond' },
  { en: 'Eugene', pt: 'Eugênio' },
  { en: 'Eustace', pt: 'Eustáquio' },
  { en: 'Ezekiel', pt: 'Ezequiel' },
  { en: 'Fabian', pt: 'Fabiano' },
  { en: 'Faith', pt: 'Fidélia' },
  { en: 'Faustina', pt: 'Faustina' },
  { en: 'Felicity', pt: 'Felicidade' },
  { en: 'Ferdinand', pt: 'Fernando' },
  { en: 'Flavia', pt: 'Flávia' },
  { en: 'Florian', pt: 'Floriano' },
  { en: 'Galahad', pt: 'Galahad' },
  { en: 'Gaspard', pt: 'Gaspar' },
  { en: 'Gavin', pt: 'Gavin' },
  { en: 'Genevieve', pt: 'Genoveva' },
  { en: 'Geoffrey', pt: 'Geofredo' },
  { en: 'Giles', pt: 'Egídio' },
  { en: 'Gloria', pt: 'Glória' },
  { en: 'Godfrey', pt: 'Godofredo' },
  { en: 'Grace', pt: 'Graça' },
  { en: 'Gregory', pt: 'Gregório' },
  { en: 'Gwen', pt: 'Gwen' },
  { en: 'Hamilton', pt: 'Hamilton' },
  { en: 'Harold', pt: 'Haroldo' },
  { en: 'Harriet', pt: 'Henriqueta' },
  { en: 'Heath', pt: 'Heath' },
  { en: 'Hera', pt: 'Hera' },
  { en: 'Hercules', pt: 'Hércules' },
  { en: 'Herman', pt: 'Hermano' },
  { en: 'Hilary', pt: 'Hilário' },
  { en: 'Hilda', pt: 'Hilda' },
  { en: 'Homer', pt: 'Homero' },
  { en: 'Horatio', pt: 'Horácio' },
  { en: 'Hubert', pt: 'Huberto' },
  { en: 'Icarus', pt: 'Ícaro' },
  { en: 'Ida', pt: 'Ida' },
  { en: 'Ignatius', pt: 'Inácio' },
  { en: 'Igor', pt: 'Igor' },
  { en: 'Immanuel', pt: 'Imanuel' },
  { en: 'Ingrid', pt: 'Ingrid' },
  { en: 'Innocent', pt: 'Inocêncio' },
  { en: 'Irene', pt: 'Irene' },
  { en: 'Iris', pt: 'Íris' },
  { en: 'Isaac', pt: 'Isaque' },
  { en: 'Isidore', pt: 'Isidoro' },
  { en: 'Ivan', pt: 'Ivan' },
  { en: 'Ivor', pt: 'Ivor' },
  { en: 'Ivy', pt: 'Ivy' },
  { en: 'Jade', pt: 'Jade' },
  { en: 'Jasmine', pt: 'Jasmim' },
  { en: 'Jason', pt: 'Jason' },
  { en: 'Jeffrey', pt: 'Jefrei' },
  { en: 'Jennifer', pt: 'Jennifer' },
  { en: 'Jerome', pt: 'Jerônimo' },
  { en: 'Jessica', pt: 'Jéssica' },
  { en: 'Jim', pt: 'Jim' },
  { en: 'Joachim', pt: 'Joaquim' },
  { en: 'Joel', pt: 'Joel' },
  { en: 'Jonas', pt: 'Jonas' },
  { en: 'Jonathan', pt: 'Jônatas' },
  { en: 'Joshua', pt: 'Josué' },
  { en: 'Joy', pt: 'Joia' },
  { en: 'Joyce', pt: 'Joice' },
  { en: 'Judah', pt: 'Judá' },
  { en: 'Judith', pt: 'Judite' },
  { en: 'Julia', pt: 'Júlia' },
  { en: 'June', pt: 'Junia' },
  { en: 'Justin', pt: 'Justino' },
  { en: 'Kane', pt: 'Kane' },
  { en: 'Karina', pt: 'Karina' },
  { en: 'Keira', pt: 'Keira' },
  { en: 'Keith', pt: 'Keith' },
  { en: 'Ken', pt: 'Ken' },
  { en: 'Kenneth', pt: 'Keneto' },
  { en: 'Kevin', pt: 'Kevin' },
  { en: 'Kirk', pt: 'Kirk' },
  { en: 'Klaus', pt: 'Klaus' },
  { en: 'Laura', pt: 'Laura' },
  { en: 'Lazarus', pt: 'Lázaro' },
  { en: 'Leander', pt: 'Leandro' },
  { en: 'Leila', pt: 'Leila' },
  { en: 'Leo', pt: 'Leo' },
  { en: 'Leonard', pt: 'Leonardo' },
  { en: 'Leopold', pt: 'Leopoldo' },
  { en: 'Leslie', pt: 'Lésli' },
  { en: 'Liam', pt: 'Liam' },
  { en: 'Lidia', pt: 'Lídia' },
  { en: 'Lily', pt: 'Lília' },
  { en: 'Lincoln', pt: 'Lincoln' },
  { en: 'Linus', pt: 'Lino' },
  { en: 'Livia', pt: 'Lívia' },
  { en: 'Lloyd', pt: 'Lloyd' },
  { en: 'Logan', pt: 'Logan' },
  { en: 'Lois', pt: 'Loide' },
  { en: 'Loretta', pt: 'Loreta' },
  { en: 'Louisa', pt: 'Luísa' },
  { en: 'Lowell', pt: 'Lowell' },
  { en: 'Lucas', pt: 'Lucas' },
  { en: 'Lucy', pt: 'Lúcia' },
  { en: 'Luigi', pt: 'Luigi' },
  { en: 'Luke', pt: 'Lucas' },
  { en: 'Lydia', pt: 'Lídia' },
  { en: 'Mabel', pt: 'Mabel' },
  { en: 'Magnus', pt: 'Magno' },
  { en: 'Malachi', pt: 'Malaquias' },
  { en: 'Manfred', pt: 'Manfredo' },
  { en: 'Marcel', pt: 'Marcelo' },
  { en: 'Marco', pt: 'Marco' },
  { en: 'Mario', pt: 'Mário' },
  { en: 'Martin', pt: 'Martim' },
  { en: 'Matilda', pt: 'Matilde' },
  { en: 'Maurice', pt: 'Maurício' },
  { en: 'Max', pt: 'Max' },
  { en: 'Maximilian', pt: 'Maximiliano' },
  { en: 'Maxwell', pt: 'Maxuel' },
  { en: 'May', pt: 'Maia' },
  { en: 'Melanie', pt: 'Melânia' },
  { en: 'Melchior', pt: 'Melchior' },
  { en: 'Merlin', pt: 'Merlin' },
  { en: 'Micah', pt: 'Micael' },
  { en: 'Miles', pt: 'Milo' },
  { en: 'Millicent', pt: 'Melisenda' },
  { en: 'Milo', pt: 'Milo' },
  { en: 'Milton', pt: 'Milton' },
  { en: 'Miranda', pt: 'Miranda' },
  { en: 'Moira', pt: 'Moira' },
  { en: 'Monica', pt: 'Mônica' },
  { en: 'Mordecai', pt: 'Mardoqueu' },
  { en: 'Morgan', pt: 'Morgan' },
  { en: 'Moses', pt: 'Moisés' },
  { en: 'Muriel', pt: 'Muriel' },
  { en: 'Myra', pt: 'Maira' },
  { en: 'Nadia', pt: 'Nádia' },
  { en: 'Nancy', pt: 'Nanci' },
  { en: 'Naomi', pt: 'Noemi' },
  { en: 'Neil', pt: 'Neil' },
  { en: 'Nicholas', pt: 'Nicolau' },
  { en: 'Nigel', pt: 'Nigel' },
  { en: 'Nina', pt: 'Nina' },
  { en: 'Noah', pt: 'Noé' },
  { en: 'Noel', pt: 'Noel' },
  { en: 'Nora', pt: 'Nora' },
  { en: 'Norman', pt: 'Normando' },
  { en: 'Octavia', pt: 'Octávia' },
  { en: 'Odin', pt: 'Odin' },
  { en: 'Olaf', pt: 'Olaf' },
  { en: 'Olivia', pt: 'Olívia' },
  { en: 'Olympia', pt: 'Olímpia' },
  { en: 'Ophelia', pt: 'Ofélia' },
  { en: 'Orion', pt: 'Orion' },
  { en: 'Orville', pt: 'Orville' },
  { en: 'Osiris', pt: 'Osíris' },
  { en: 'Oswald', pt: 'Osvaldo' },
  { en: 'Othello', pt: 'Otelo' },
  { en: 'Otto', pt: 'Otto' },
  { en: 'Pandora', pt: 'Pandora' },
  { en: 'Paschal', pt: 'Pascoal' },
  { en: 'Patrick', pt: 'Patrício' },
  { en: 'Paula', pt: 'Paula' },
  { en: 'Phoebe', pt: 'Febe' },
  { en: 'Piers', pt: 'Piers' },
  { en: 'Plato', pt: 'Platão' },
  { en: 'Polly', pt: 'Poliana' },
  { en: 'Prosper', pt: 'Próspero' },
  { en: 'Rachel', pt: 'Raquel' },
  { en: 'Rafael', pt: 'Rafael' },
  { en: 'Rainer', pt: 'Rainer' },
  { en: 'Ralph', pt: 'Ralf' },
  { en: 'Raul', pt: 'Raul' },
  { en: 'Rebecca', pt: 'Rebeca' },
  { en: 'Regina', pt: 'Regina' },
  { en: 'Reginald', pt: 'Reginaldo' },
  { en: 'Reid', pt: 'Reid' },
  { en: 'Remus', pt: 'Remo' },
  { en: 'Renata', pt: 'Renata' },
  { en: 'Rene', pt: 'René' },
  { en: 'Reuben', pt: 'Rubens' },
  { en: 'Rex', pt: 'Rex' },
  { en: 'Rhea', pt: 'Reia' },
  { en: 'Rhoda', pt: 'Roda' },
  { en: 'Rita', pt: 'Rita' },
  { en: 'Robin', pt: 'Robin' },
  { en: 'Rodney', pt: 'Rodinei' },
  { en: 'Roland', pt: 'Rolando' },
  { en: 'Romeo', pt: 'Romeu' },
  { en: 'Ronan', pt: 'Ronan' },
  { en: 'Rosalia', pt: 'Rosália' },
  { en: 'Rosemary', pt: 'Rosamaria' },
  { en: 'Rowan', pt: 'Rowan' },
  { en: 'Ruby', pt: 'Rubi' },
  { en: 'Rudolph', pt: 'Rodolfo' },
  { en: 'Rufus', pt: 'Rufo' },
  { en: 'Rupert', pt: 'Ruperto' },
  { en: 'Russell', pt: 'Russel' },
  { en: 'Ruth', pt: 'Rute' },
  { en: 'Sabina', pt: 'Sabina' },
  { en: 'Sabrina', pt: 'Sabrina' },
  { en: 'Sacha', pt: 'Sacha' },
  { en: 'Sampson', pt: 'Sansão' },
  { en: 'Santiago', pt: 'Santiago' },
  { en: 'Sara', pt: 'Sara' },
  { en: 'Savannah', pt: 'Savana' },
  { en: 'Scarlett', pt: 'Escarlete' },
  { en: 'Scott', pt: 'Scott' },
  { en: 'Selma', pt: 'Selma' },
  { en: 'Seraphina', pt: 'Serafina' },
  { en: 'Serena', pt: 'Serena' },
  { en: 'Seth', pt: 'Sete' },
  { en: 'Shane', pt: 'Shane' },
  { en: 'Shannon', pt: 'Shannon' },
  { en: 'Sharon', pt: 'Sharon' },
  { en: 'Sheldon', pt: 'Sheldon' },
  { en: 'Sherlock', pt: 'Sherlock' },
  { en: 'Sonia', pt: 'Sônia' },
  { en: 'Sven', pt: 'Sven' },
  { en: 'Sylvester', pt: 'Silvestre' },
  { en: 'Teresa', pt: 'Teresa' },
  { en: 'Thaddeus', pt: 'Tadeu' },
  { en: 'Thelma', pt: 'Telma' },
  { en: 'Thomas', pt: 'Tomás' },
  { en: 'Timothy', pt: 'Timóteo' },
  { en: 'Tristan', pt: 'Tristão' },
  { en: 'Troy', pt: 'Troy' },
  { en: 'Tybalt', pt: 'Teobaldo' },
  { en: 'Ulysses', pt: 'Ulisses' },
  { en: 'Urban', pt: 'Urbano' },
  { en: 'Valdemar', pt: 'Valdemar' },
  { en: 'Valentine', pt: 'Valentim' },
  { en: 'Valeria', pt: 'Valéria' },
  { en: 'Valery', pt: 'Valério' },
  { en: 'Vera', pt: 'Vera' },
  { en: 'Veronica', pt: 'Verônica' },
  { en: 'Victoria', pt: 'Vitória' },
  { en: 'Viola', pt: 'Viola' },
  { en: 'Violet', pt: 'Violeta' },
  { en: 'Virgil', pt: 'Virgílio' },
  { en: 'Virginia', pt: 'Virgínia' },
  { en: 'Vivian', pt: 'Viviane' },
  { en: 'Wallace', pt: 'Wallace' },
  { en: 'Wanda', pt: 'Wanda' },
  { en: 'Warren', pt: 'Warren' },
  { en: 'Wesley', pt: 'Wesley' },
  { en: 'Wilfred', pt: 'Vilfredo' },
  { en: 'Willie', pt: 'Willie' },
  { en: 'Wilson', pt: 'Wilson' },
  { en: 'Winston', pt: 'Winston' },
  { en: 'Wyatt', pt: 'Wyatt' },
  { en: 'Xander', pt: 'Xander' },
  { en: 'Xenia', pt: 'Xênia' },
  { en: 'Xerxes', pt: 'Xerxes' },
  { en: 'Yara', pt: 'Yara' },
  { en: 'Yasmine', pt: 'Yasmine' },
  { en: 'Zelda', pt: 'Zelda' },
  { en: 'Zena', pt: 'Zena' },
  { en: 'Zoe', pt: 'Zoe' },
  { en: 'Zola', pt: 'Zola' },
];
